version: '3.3'
services:
  django-jenkins:
    container_name: django-jenkins
    image: jmdpsysadmin/django_tutorial:13
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      HOST: db_django_jenkins
      USUARIO: django
      CONTRA: django
      BASE_DATOS: django
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@gmail.com
    ports:
      - 8085:8005
    depends_on:
      - db_django_jenkins
  db_django_jenkins:
    container_name: db_django_jenkins
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django
    volumes:
      - mariadb_data_django_jenkins:/var/lib/mysql
volumes:
    mariadb_data_django_jenkins:
